### ISSUE TITLE
Using `@web3-storage/w3up-client` in Nest JS

### ISSUE THREAD

**Issue by nabeelraza-7** [storacha/w3up#1530]
I'm trying to use the JS client in Nest JS. It gives me the following error:

```js
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/nabeel/code/custom-agents-backend/node_modules/@web3-storage/w3up-client/dist/src/index.node.js from /home/nabeel/code/custom-agents-backend/dist/agent-config/agent-config.controller.js not supported.
Instead change the require of index.node.js in /home/nabeel/code/custom-agents-backend/dist/agent-config/agent-config.controller.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/nabeel/code/custom-agents-backend/dist/agent-config/agent-config.controller.js:15:23)
    at Object.<anonymous> (/home/nabeel/code/custom-agents-backend/dist/agent-config/agent-config.module.js:12:35)
    at Object.<anonymous> (/home/nabeel/code/custom-agents-backend/dist/app.module.js:16:31)
    at Object.<anonymous> (/home/nabeel/code/custom-agents-backend/dist/main.js:4:22) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.20.3
```

If I change `package.json` and `tsconfig.json`, it gives me module not found error like this:

```
src/main.ts:2:27 - error TS2307: Cannot find module './app.module' or its corresponding type declarations.

2 import { AppModule } from "./app.module";
```

I added `type: module` in `package.json` and `module=nodenext` and `moduleResolution=nodenext` to `tsconfig.json` according to this answer at stackoverflow: https://stackoverflow.com/questions/70800567/return-oldm-filename-error-err-require-esm-require-of-es-module/75721650#75721650

**Comment by Filip3Dev** [comment]
Any response?

**Comment by naveenneelamwip2** [comment]
Update on this please, it's been long time, I am also facing same issue, tried dynamic module importing also still not working

**Comment by nabeelraza-7** [comment]
I somehow made it work. Here's my `tsconfig.json`:
```js
{
  "compilerOptions": {
    "module": "node16",
    "moduleResolution": "node16",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "ES2021",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "skipLibCheck": true,
    "strictNullChecks": false,
    "noImplicitAny": false,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "noFallthroughCasesInSwitch": false,
    "esModuleInterop": true
  },
  "ts-node": {
    "esm": true
  }
}
```
`package.json`
```js
{
  "name": "backend-service",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    ...
  },
  "dependencies": {
    ...
  },
  "devDependencies": {
    ...
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}
```

You will have to use `await` to get the imports. For that, I have created a function which returns the client which you can use just like they do in the documentation:
```js
  private async getWeb3Client() {
    const web3Storage = await import('@web3-storage/w3up-client');
    const { StoreMemory } = await import(
      '@web3-storage/w3up-client/stores/memory'
    );
    const Proof = await import('@web3-storage/w3up-client/proof');
    const { Signer } = await import(
      '@web3-storage/w3up-client/principal/ed25519'
    );

    const principal = Signer.parse(process.env.WEB3_PRIVATE_KEY);
    const store = new StoreMemory();
    const client = await web3Storage.create({ principal, store });
    const proof = await Proof.parse(process.env.WEB3_PROOF);
    const space = await client.addSpace(proof);
    await client.setCurrentSpace(space.did());

    return client;
  }
  ```
